"""Migração inicial

Revision ID: bac86124cca5
Revises: 
Create Date: 2025-07-06 00:21:00.823756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac86124cca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('unidade', sa.Enum('kg', 'saco', 'unidade', name='unidademedida'), nullable=False),
    sa.Column('valor_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estoque_quantidade', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('admin', 'operador', name='tipousuario'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('cpf', name='uq_usuario_cpf')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipomovimentacao'), nullable=False),
    sa.Column('quantidade', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('pix_fabiano', 'pix_maquineta', 'dinheiro', 'cartao_credito', 'cartao_debito', 'a_prazo', name='formapagamento'), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('emitida', 'cancelada', name='statusnota'), nullable=False),
    sa.Column('chave_acesso', sa.String(length=60), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso')
    )
    op.create_table('financeiro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipomovimentacao'), nullable=False),
    sa.Column('categoria', sa.Enum('venda', 'compra', 'despesa', 'salario', 'outro', name='categoriafinanceira'), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_fiscal_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_fiscais.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_fiscal_itens')
    op.drop_table('financeiro')
    op.drop_table('notas_fiscais')
    op.drop_table('movimentacoes_estoque')
    op.drop_table('usuarios')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
